# Generated by Django 5.1.5 on 2025-03-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0002_profile_date_of_birth_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
