# Generated by Django 5.2.1 on 2025-05-26 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0004_group_groupmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcgSampleValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='ecg_app.ecgsamples')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-validated_at'],
                'unique_together': {('sample', 'teacher')},
            },
        ),
    ]
