# Generated by Django 5.2.1 on 2025-05-27 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0005_ecgsamplevalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgsamplevalidation',
            name='curr_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curr_tag', to='ecg_app.ecgdoclabels'),
        ),
        migrations.AddField(
            model_name='ecgsamplevalidation',
            name='new_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_tag', to='ecg_app.ecgdoclabels'),
        ),
    ]
