# Generated by Django 5.2.2 on 2025-06-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0007_historicalecgsamplevalidation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ecgsamplesdoclabels',
            unique_together={('sample_id',)},
        ),
    ]
