# Generated by Django 5.2.2 on 2025-06-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0008_alter_ecgsamplesdoclabels_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecgsamplevalidation',
            name='is_valid',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalecgsamplevalidation',
            name='is_valid',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
