# Generated by Django 5.2.2 on 2025-06-07 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0009_alter_ecgsamplevalidation_is_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecgsamplevalidation',
            options={'ordering': ['sample']},
        ),
        migrations.AlterUniqueTogether(
            name='ecgsamplevalidation',
            unique_together={('sample',)},
        ),
        migrations.AddField(
            model_name='ecgsamplevalidation',
            name='have_been_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ecgsamplevalidation',
            name='prev_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_tag', to='ecg_app.ecgdoclabels'),
        ),
        migrations.CreateModel(
            name='ValidationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_new_tag', to='ecg_app.ecgdoclabels')),
                ('prev_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_prev_tag', to='ecg_app.ecgdoclabels')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_history', to='ecg_app.ecgsamples')),
                ('validated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_history', to=settings.AUTH_USER_MODEL)),
                ('validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ecg_app.ecgsamplevalidation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='HistoricalEcgSampleValidation',
        ),
        migrations.RemoveField(
            model_name='ecgsamplevalidation',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='ecgsamplevalidation',
            name='curr_tag',
        ),
        migrations.RemoveField(
            model_name='ecgsamplevalidation',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='ecgsamplevalidation',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='ecgsamplevalidation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ecgsamplevalidation',
            name='validated_at',
        ),
    ]
