# Generated by Django 5.1.3 on 2025-07-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0010_alter_ecgsamplevalidation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgsamples',
            name='difficulty_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
