# Generated by Django 5.2.4 on 2025-07-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0011_ecgsamples_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
