# Generated by Django 5.2.4 on 2025-07-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0012_questionattempt_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
