# Generated by Django 5.1.4 on 2024-12-21 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcgDocLabels',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_desc', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EcgSamples',
            fields=[
                ('sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EcgSnomed',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_code', models.IntegerField(unique=True)),
                ('label_desc', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EcgSamplesDocLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='app.ecgdoclabels')),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_labels', to='app.ecgsamples')),
            ],
        ),
        migrations.CreateModel(
            name='EcgSamplesSnomed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snomed_labels', to='app.ecgsamples')),
                ('label_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='app.ecgsnomed')),
            ],
        ),
    ]
