# Frontend Dockerfile
FROM node:22.11.0

ENV REACT_APP_DEBUG=true
ENV REACT_APP_API_BASE_URL="http://localhost:8000/api"
ENV CHOKIDAR_USEPOLLING=true
ENV WDS_SOCKET_PORT=0

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json /app/
RUN npm install --loglevel error

# Expose application port
EXPOSE 3000

# Start the app
CMD ["npm", "run", "start-watch"]