services:
  database:
    image: postgres:latest
    container_name: ecg-database-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    container_name: ecg-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - database
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - DATASET_SAMPLES_PATH=/dataset/samples_dev  # directory with ECG samples
      - DATASET_SNOMED_PATH=/dataset/snomed/relevant.csv  # file with relevant SNOMED codes
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./dataset:/dataset
    stdin_open: true
    tty: true

  frontend:
    container_name: ecg-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/build
    stdin_open: true
    tty: true

volumes:
  db_data: