--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: ecg_app_choice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ecg_app_choice (
    id bigint NOT NULL,
    text character varying(255) NOT NULL,
    is_correct boolean NOT NULL,
    question_id bigint NOT NULL
);


ALTER TABLE public.ecg_app_choice OWNER TO postgres;

--
-- Name: ecg_app_choice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ecg_app_choice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecg_app_choice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecg_app_ecgdoclabels; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ecg_app_ecgdoclabels (
    label_id integer NOT NULL,
    label_desc character varying(255) NOT NULL
);


ALTER TABLE public.ecg_app_ecgdoclabels OWNER TO postgres;

--
-- Name: ecg_app_ecgdoclabels_label_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ecg_app_ecgdoclabels ALTER COLUMN label_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecg_app_ecgdoclabels_label_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecg_app_ecgsamples; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ecg_app_ecgsamples (
    sample_id integer NOT NULL,
    sample_path character varying(255) NOT NULL,
    gender character varying(10),
    age integer,
    CONSTRAINT ecg_app_ecgsamples_age_check CHECK ((age >= 0))
);


ALTER TABLE public.ecg_app_ecgsamples OWNER TO postgres;

--
-- Name: ecg_app_ecgsamples_sample_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ecg_app_ecgsamples ALTER COLUMN sample_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecg_app_ecgsamples_sample_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecg_app_ecgsamplesdoclabels; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ecg_app_ecgsamplesdoclabels (
    id bigint NOT NULL,
    label_id_id integer NOT NULL,
    sample_id_id integer NOT NULL
);


ALTER TABLE public.ecg_app_ecgsamplesdoclabels OWNER TO postgres;

--
-- Name: ecg_app_ecgsamplesdoclabels_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ecg_app_ecgsamplesdoclabels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecg_app_ecgsamplesdoclabels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecg_app_ecgsamplessnomed; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ecg_app_ecgsamplessnomed (
    id bigint NOT NULL,
    sample_id_id integer NOT NULL,
    label_id_id integer NOT NULL
);


ALTER TABLE public.ecg_app_ecgsamplessnomed OWNER TO postgres;

--
-- Name: ecg_app_ecgsamplessnomed_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ecg_app_ecgsamplessnomed ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecg_app_ecgsamplessnomed_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecg_app_ecgsamplevalidation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ecg_app_ecgsamplevalidation (
    id bigint NOT NULL,
    is_valid boolean NOT NULL,
    comments text,
    validated_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    sample_id integer NOT NULL,
    teacher_id integer NOT NULL,
    curr_tag_id integer NOT NULL,
    new_tag_id integer NOT NULL
);


ALTER TABLE public.ecg_app_ecgsamplevalidation OWNER TO postgres;

--
-- Name: ecg_app_ecgsamplevalidation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ecg_app_ecgsamplevalidation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecg_app_ecgsamplevalidation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecg_app_ecgsnomed; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ecg_app_ecgsnomed (
    label_id integer NOT NULL,
    label_code integer NOT NULL,
    label_desc character varying(255) NOT NULL
);


ALTER TABLE public.ecg_app_ecgsnomed OWNER TO postgres;

--
-- Name: ecg_app_ecgsnomed_label_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ecg_app_ecgsnomed ALTER COLUMN label_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecg_app_ecgsnomed_label_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecg_app_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ecg_app_group (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    teacher_id integer NOT NULL
);


ALTER TABLE public.ecg_app_group OWNER TO postgres;

--
-- Name: ecg_app_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ecg_app_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecg_app_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecg_app_groupmembership; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ecg_app_groupmembership (
    id bigint NOT NULL,
    status character varying(10) NOT NULL,
    joined_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    group_id bigint NOT NULL,
    student_id integer NOT NULL
);


ALTER TABLE public.ecg_app_groupmembership OWNER TO postgres;

--
-- Name: ecg_app_groupmembership_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ecg_app_groupmembership ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecg_app_groupmembership_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecg_app_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ecg_app_profile (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    date_of_birth date,
    gender character varying(10),
    role character varying(10) NOT NULL
);


ALTER TABLE public.ecg_app_profile OWNER TO postgres;

--
-- Name: ecg_app_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ecg_app_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecg_app_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecg_app_question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ecg_app_question (
    id bigint NOT NULL,
    question_text text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    ecg_sample_id integer NOT NULL,
    quiz_id bigint NOT NULL
);


ALTER TABLE public.ecg_app_question OWNER TO postgres;

--
-- Name: ecg_app_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ecg_app_question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecg_app_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecg_app_questionattempt; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ecg_app_questionattempt (
    id bigint NOT NULL,
    is_correct boolean NOT NULL,
    question_id bigint NOT NULL,
    selected_choice_id bigint,
    quiz_attempt_id bigint NOT NULL
);


ALTER TABLE public.ecg_app_questionattempt OWNER TO postgres;

--
-- Name: ecg_app_questionattempt_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ecg_app_questionattempt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecg_app_questionattempt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecg_app_quiz; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ecg_app_quiz (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.ecg_app_quiz OWNER TO postgres;

--
-- Name: ecg_app_quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ecg_app_quiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecg_app_quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecg_app_quizattempt; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ecg_app_quizattempt (
    id bigint NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    quiz_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.ecg_app_quizattempt OWNER TO postgres;

--
-- Name: ecg_app_quizattempt_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ecg_app_quizattempt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecg_app_quizattempt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: ecg_app_choice ecg_app_choice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_choice
    ADD CONSTRAINT ecg_app_choice_pkey PRIMARY KEY (id);


--
-- Name: ecg_app_ecgdoclabels ecg_app_ecgdoclabels_label_desc_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgdoclabels
    ADD CONSTRAINT ecg_app_ecgdoclabels_label_desc_key UNIQUE (label_desc);


--
-- Name: ecg_app_ecgdoclabels ecg_app_ecgdoclabels_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgdoclabels
    ADD CONSTRAINT ecg_app_ecgdoclabels_pkey PRIMARY KEY (label_id);


--
-- Name: ecg_app_ecgsamples ecg_app_ecgsamples_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsamples
    ADD CONSTRAINT ecg_app_ecgsamples_pkey PRIMARY KEY (sample_id);


--
-- Name: ecg_app_ecgsamplesdoclabels ecg_app_ecgsamplesdoclabels_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsamplesdoclabels
    ADD CONSTRAINT ecg_app_ecgsamplesdoclabels_pkey PRIMARY KEY (id);


--
-- Name: ecg_app_ecgsamplessnomed ecg_app_ecgsamplessnomed_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsamplessnomed
    ADD CONSTRAINT ecg_app_ecgsamplessnomed_pkey PRIMARY KEY (id);


--
-- Name: ecg_app_ecgsamplevalidation ecg_app_ecgsamplevalidation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsamplevalidation
    ADD CONSTRAINT ecg_app_ecgsamplevalidation_pkey PRIMARY KEY (id);


--
-- Name: ecg_app_ecgsamplevalidation ecg_app_ecgsamplevalidation_sample_id_teacher_id_f26d5630_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsamplevalidation
    ADD CONSTRAINT ecg_app_ecgsamplevalidation_sample_id_teacher_id_f26d5630_uniq UNIQUE (sample_id, teacher_id);


--
-- Name: ecg_app_ecgsnomed ecg_app_ecgsnomed_label_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsnomed
    ADD CONSTRAINT ecg_app_ecgsnomed_label_code_key UNIQUE (label_code);


--
-- Name: ecg_app_ecgsnomed ecg_app_ecgsnomed_label_desc_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsnomed
    ADD CONSTRAINT ecg_app_ecgsnomed_label_desc_key UNIQUE (label_desc);


--
-- Name: ecg_app_ecgsnomed ecg_app_ecgsnomed_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsnomed
    ADD CONSTRAINT ecg_app_ecgsnomed_pkey PRIMARY KEY (label_id);


--
-- Name: ecg_app_group ecg_app_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_group
    ADD CONSTRAINT ecg_app_group_pkey PRIMARY KEY (id);


--
-- Name: ecg_app_groupmembership ecg_app_groupmembership_group_id_student_id_10adf1ca_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_groupmembership
    ADD CONSTRAINT ecg_app_groupmembership_group_id_student_id_10adf1ca_uniq UNIQUE (group_id, student_id);


--
-- Name: ecg_app_groupmembership ecg_app_groupmembership_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_groupmembership
    ADD CONSTRAINT ecg_app_groupmembership_pkey PRIMARY KEY (id);


--
-- Name: ecg_app_profile ecg_app_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_profile
    ADD CONSTRAINT ecg_app_profile_pkey PRIMARY KEY (id);


--
-- Name: ecg_app_profile ecg_app_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_profile
    ADD CONSTRAINT ecg_app_profile_user_id_key UNIQUE (user_id);


--
-- Name: ecg_app_question ecg_app_question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_question
    ADD CONSTRAINT ecg_app_question_pkey PRIMARY KEY (id);


--
-- Name: ecg_app_questionattempt ecg_app_questionattempt_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_questionattempt
    ADD CONSTRAINT ecg_app_questionattempt_pkey PRIMARY KEY (id);


--
-- Name: ecg_app_quiz ecg_app_quiz_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_quiz
    ADD CONSTRAINT ecg_app_quiz_pkey PRIMARY KEY (id);


--
-- Name: ecg_app_quizattempt ecg_app_quizattempt_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_quizattempt
    ADD CONSTRAINT ecg_app_quizattempt_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: ecg_app_choice_question_id_52f4e6b3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_choice_question_id_52f4e6b3 ON public.ecg_app_choice USING btree (question_id);


--
-- Name: ecg_app_ecgdoclabels_label_desc_73b5e35b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_ecgdoclabels_label_desc_73b5e35b_like ON public.ecg_app_ecgdoclabels USING btree (label_desc varchar_pattern_ops);


--
-- Name: ecg_app_ecgsamplesdoclabels_label_id_id_82266a4f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_ecgsamplesdoclabels_label_id_id_82266a4f ON public.ecg_app_ecgsamplesdoclabels USING btree (label_id_id);


--
-- Name: ecg_app_ecgsamplesdoclabels_sample_id_id_16d76fc9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_ecgsamplesdoclabels_sample_id_id_16d76fc9 ON public.ecg_app_ecgsamplesdoclabels USING btree (sample_id_id);


--
-- Name: ecg_app_ecgsamplessnomed_label_id_id_9b34e161; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_ecgsamplessnomed_label_id_id_9b34e161 ON public.ecg_app_ecgsamplessnomed USING btree (label_id_id);


--
-- Name: ecg_app_ecgsamplessnomed_sample_id_id_0924526c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_ecgsamplessnomed_sample_id_id_0924526c ON public.ecg_app_ecgsamplessnomed USING btree (sample_id_id);


--
-- Name: ecg_app_ecgsamplevalidation_curr_tag_id_83ea7508; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_ecgsamplevalidation_curr_tag_id_83ea7508 ON public.ecg_app_ecgsamplevalidation USING btree (curr_tag_id);


--
-- Name: ecg_app_ecgsamplevalidation_new_tag_id_e06a6ec9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_ecgsamplevalidation_new_tag_id_e06a6ec9 ON public.ecg_app_ecgsamplevalidation USING btree (new_tag_id);


--
-- Name: ecg_app_ecgsamplevalidation_sample_id_38eb0d1f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_ecgsamplevalidation_sample_id_38eb0d1f ON public.ecg_app_ecgsamplevalidation USING btree (sample_id);


--
-- Name: ecg_app_ecgsamplevalidation_teacher_id_f6c56545; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_ecgsamplevalidation_teacher_id_f6c56545 ON public.ecg_app_ecgsamplevalidation USING btree (teacher_id);


--
-- Name: ecg_app_ecgsnomed_label_desc_59f927f5_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_ecgsnomed_label_desc_59f927f5_like ON public.ecg_app_ecgsnomed USING btree (label_desc varchar_pattern_ops);


--
-- Name: ecg_app_group_teacher_id_9c81c536; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_group_teacher_id_9c81c536 ON public.ecg_app_group USING btree (teacher_id);


--
-- Name: ecg_app_groupmembership_group_id_92903890; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_groupmembership_group_id_92903890 ON public.ecg_app_groupmembership USING btree (group_id);


--
-- Name: ecg_app_groupmembership_student_id_ee4035b5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_groupmembership_student_id_ee4035b5 ON public.ecg_app_groupmembership USING btree (student_id);


--
-- Name: ecg_app_question_ecg_sample_id_4fd03a0e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_question_ecg_sample_id_4fd03a0e ON public.ecg_app_question USING btree (ecg_sample_id);


--
-- Name: ecg_app_question_quiz_id_da19e1c6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_question_quiz_id_da19e1c6 ON public.ecg_app_question USING btree (quiz_id);


--
-- Name: ecg_app_questionattempt_question_id_90a50596; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_questionattempt_question_id_90a50596 ON public.ecg_app_questionattempt USING btree (question_id);


--
-- Name: ecg_app_questionattempt_quiz_attempt_id_9f980262; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_questionattempt_quiz_attempt_id_9f980262 ON public.ecg_app_questionattempt USING btree (quiz_attempt_id);


--
-- Name: ecg_app_questionattempt_selected_choice_id_ed09d479; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_questionattempt_selected_choice_id_ed09d479 ON public.ecg_app_questionattempt USING btree (selected_choice_id);


--
-- Name: ecg_app_quizattempt_quiz_id_a91a224d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_quizattempt_quiz_id_a91a224d ON public.ecg_app_quizattempt USING btree (quiz_id);


--
-- Name: ecg_app_quizattempt_user_id_43aff9b9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ecg_app_quizattempt_user_id_43aff9b9 ON public.ecg_app_quizattempt USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_choice ecg_app_choice_question_id_52f4e6b3_fk_ecg_app_question_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_choice
    ADD CONSTRAINT ecg_app_choice_question_id_52f4e6b3_fk_ecg_app_question_id FOREIGN KEY (question_id) REFERENCES public.ecg_app_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_ecgsamplesdoclabels ecg_app_ecgsamplesdo_label_id_id_82266a4f_fk_ecg_app_e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsamplesdoclabels
    ADD CONSTRAINT ecg_app_ecgsamplesdo_label_id_id_82266a4f_fk_ecg_app_e FOREIGN KEY (label_id_id) REFERENCES public.ecg_app_ecgdoclabels(label_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_ecgsamplesdoclabels ecg_app_ecgsamplesdo_sample_id_id_16d76fc9_fk_ecg_app_e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsamplesdoclabels
    ADD CONSTRAINT ecg_app_ecgsamplesdo_sample_id_id_16d76fc9_fk_ecg_app_e FOREIGN KEY (sample_id_id) REFERENCES public.ecg_app_ecgsamples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_ecgsamplessnomed ecg_app_ecgsamplessn_label_id_id_9b34e161_fk_ecg_app_e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsamplessnomed
    ADD CONSTRAINT ecg_app_ecgsamplessn_label_id_id_9b34e161_fk_ecg_app_e FOREIGN KEY (label_id_id) REFERENCES public.ecg_app_ecgsnomed(label_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_ecgsamplessnomed ecg_app_ecgsamplessn_sample_id_id_0924526c_fk_ecg_app_e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsamplessnomed
    ADD CONSTRAINT ecg_app_ecgsamplessn_sample_id_id_0924526c_fk_ecg_app_e FOREIGN KEY (sample_id_id) REFERENCES public.ecg_app_ecgsamples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_ecgsamplevalidation ecg_app_ecgsampleval_curr_tag_id_83ea7508_fk_ecg_app_e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsamplevalidation
    ADD CONSTRAINT ecg_app_ecgsampleval_curr_tag_id_83ea7508_fk_ecg_app_e FOREIGN KEY (curr_tag_id) REFERENCES public.ecg_app_ecgdoclabels(label_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_ecgsamplevalidation ecg_app_ecgsampleval_new_tag_id_e06a6ec9_fk_ecg_app_e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsamplevalidation
    ADD CONSTRAINT ecg_app_ecgsampleval_new_tag_id_e06a6ec9_fk_ecg_app_e FOREIGN KEY (new_tag_id) REFERENCES public.ecg_app_ecgdoclabels(label_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_ecgsamplevalidation ecg_app_ecgsampleval_sample_id_38eb0d1f_fk_ecg_app_e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsamplevalidation
    ADD CONSTRAINT ecg_app_ecgsampleval_sample_id_38eb0d1f_fk_ecg_app_e FOREIGN KEY (sample_id) REFERENCES public.ecg_app_ecgsamples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_ecgsamplevalidation ecg_app_ecgsamplevalidation_teacher_id_f6c56545_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_ecgsamplevalidation
    ADD CONSTRAINT ecg_app_ecgsamplevalidation_teacher_id_f6c56545_fk_auth_user_id FOREIGN KEY (teacher_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_group ecg_app_group_teacher_id_9c81c536_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_group
    ADD CONSTRAINT ecg_app_group_teacher_id_9c81c536_fk_auth_user_id FOREIGN KEY (teacher_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_groupmembership ecg_app_groupmembership_group_id_92903890_fk_ecg_app_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_groupmembership
    ADD CONSTRAINT ecg_app_groupmembership_group_id_92903890_fk_ecg_app_group_id FOREIGN KEY (group_id) REFERENCES public.ecg_app_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_groupmembership ecg_app_groupmembership_student_id_ee4035b5_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_groupmembership
    ADD CONSTRAINT ecg_app_groupmembership_student_id_ee4035b5_fk_auth_user_id FOREIGN KEY (student_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_profile ecg_app_profile_user_id_7aeef4af_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_profile
    ADD CONSTRAINT ecg_app_profile_user_id_7aeef4af_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_question ecg_app_question_ecg_sample_id_4fd03a0e_fk_ecg_app_e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_question
    ADD CONSTRAINT ecg_app_question_ecg_sample_id_4fd03a0e_fk_ecg_app_e FOREIGN KEY (ecg_sample_id) REFERENCES public.ecg_app_ecgsamples(sample_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_question ecg_app_question_quiz_id_da19e1c6_fk_ecg_app_quiz_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_question
    ADD CONSTRAINT ecg_app_question_quiz_id_da19e1c6_fk_ecg_app_quiz_id FOREIGN KEY (quiz_id) REFERENCES public.ecg_app_quiz(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_questionattempt ecg_app_questionatte_question_id_90a50596_fk_ecg_app_q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_questionattempt
    ADD CONSTRAINT ecg_app_questionatte_question_id_90a50596_fk_ecg_app_q FOREIGN KEY (question_id) REFERENCES public.ecg_app_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_questionattempt ecg_app_questionatte_quiz_attempt_id_9f980262_fk_ecg_app_q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_questionattempt
    ADD CONSTRAINT ecg_app_questionatte_quiz_attempt_id_9f980262_fk_ecg_app_q FOREIGN KEY (quiz_attempt_id) REFERENCES public.ecg_app_quizattempt(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_questionattempt ecg_app_questionatte_selected_choice_id_ed09d479_fk_ecg_app_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_questionattempt
    ADD CONSTRAINT ecg_app_questionatte_selected_choice_id_ed09d479_fk_ecg_app_c FOREIGN KEY (selected_choice_id) REFERENCES public.ecg_app_choice(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_quizattempt ecg_app_quizattempt_quiz_id_a91a224d_fk_ecg_app_quiz_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_quizattempt
    ADD CONSTRAINT ecg_app_quizattempt_quiz_id_a91a224d_fk_ecg_app_quiz_id FOREIGN KEY (quiz_id) REFERENCES public.ecg_app_quiz(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecg_app_quizattempt ecg_app_quizattempt_user_id_43aff9b9_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ecg_app_quizattempt
    ADD CONSTRAINT ecg_app_quizattempt_user_id_43aff9b9_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

